#!/usr/bin/env python3
"""
Sporting Pearls — About-menu nav re-point (Phase 1).

Re-points 4 dead About-dropdown links to their real targets:

  our-story.html       ->  about-us.html#our-story
  vision-mission.html  ->  about-us.html#vision-mission
  core-values.html     ->  about-us.html#core-values
  partner-with-us.html ->  partners.html

The mobile menu is generated by the shared JS from the same hrefs, so this one
replacement fixes desktop + mobile in a single pass.

Usage:
  python3 repoint_nav.py <folder>            # re-point every .html in folder (in place)
  python3 repoint_nav.py <folder> --dry-run  # show what would change
"""
import sys, glob, os, io

REP = [
    ('href="our-story.html"',       'href="about-us.html#our-story"'),
    ('href="vision-mission.html"',  'href="about-us.html#vision-mission"'),
    ('href="core-values.html"',     'href="about-us.html#core-values"'),
    ('href="partner-with-us.html"', 'href="partners.html"'),
]

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    folder = sys.argv[1]
    dry = '--dry-run' in sys.argv
    total = 0
    for path in sorted(glob.glob(os.path.join(folder, '*.html'))):
        with io.open(path, encoding='utf-8') as f:
            src = f.read()
        counts = []
        out = src
        for a, b in REP:
            n = out.count(a)
            if n:
                out = out.replace(a, b)
                counts.append(f'{a} -> {b} ({n}x)')
        if counts:
            total += len(counts)
            print(f'\n{os.path.basename(path)}:')
            for c in counts:
                print(f'   {c}')
            if not dry:
                with io.open(path, 'w', encoding='utf-8') as f:
                    f.write(out)
    print(f'\n{"[DRY RUN] " if dry else ""}Done. {total} link target(s) re-pointed.')

if __name__ == '__main__':
    main()
